[project]
name = "backend"
version = "0.1.0"
description = "Visualization of motion-capture data"
authors = [
    { name = "mathias gewissen", email = "mathias.gewissen@htw-dresden.de" },
]
readme = "README.md"
requires-python = ">=3.10,<3.11.dev0"

dependencies = [
    "fastapi>=0.110.0",
    "uvicorn[standard]>=0.29.0",
    "numpy>=1.26.0",
    "python-multipart (>=0.0.20,<0.0.21)",
    "setuptools (>=80.9.0,<81.0.0)",
    "scipy (>=1.15.3,<2.0.0)",
    "pandas (>=2.3.0,<3.0.0)",
    "upc-pymotion (>=0.2.3,<0.3.0)",
    "pyquaternion (>=0.9.9,<0.10.0)",
    "cdflib (>=1.3.4,<2.0.0)",
    "mvnx @ git+https://github.com/edscher/mvnx.git",
    "ezc3d (>=1.5.19,<2.0.0)",
    "tqdm (>=4.67.1,<5.0.0)",
    "h5py (>=3.14.0,<4.0.0)",
    "mat73 (>=0.65,<0.66)",
    # "mocap-loader @ git+https://github.com/edscher/mocap_loader",
    "mocap-loader @ git+ssh://git@github.com/edscher/mocap_loader.git",
    "bvhtoolbox (>=0.1.3,<0.2.0)",
]
[project.optional-dependencies]
dev = ["black>=24.3.0", "isort>=5.13.0", "pytest>=8.1.0"]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
